"""Presentation contracts for built-in observer metrics."""

from __future__ import annotations

from salvi.components.catalog_models import (
    MetricPopulation,
    MetricTemporalScope,
    MetricValueKind,
    ObserverMetricGroupPresentation,
    ObserverMetricPresentation,
    ObserverPresentation,
    ObserverViewKind,
)


def _metric(
    pattern: str,
    label: str,
    description: str,
    unit: str,
    value_kind: MetricValueKind,
    temporal_scope: MetricTemporalScope,
    population: MetricPopulation,
    display_group: str,
) -> ObserverMetricPresentation:
    return ObserverMetricPresentation(
        pattern=pattern,
        label=label,
        description=description,
        unit=unit,
        value_kind=value_kind,
        temporal_scope=temporal_scope,
        population=population,
        display_group=display_group,
    )


def _metric_group(
    name: str,
    label: str,
    description: str,
) -> ObserverMetricGroupPresentation:
    return ObserverMetricGroupPresentation(
        name=name,
        label=label,
        description=description,
    )


_OBSERVER_PRESENTATIONS: dict[str, ObserverPresentation] = {
    "search_progress": ObserverPresentation(
        view_kind=ObserverViewKind.PROGRESS,
        title="Search progress",
        metric_patterns=("search.evaluations",),
        empty_message="Progress appears after the first evaluated batch.",
        x_axis_label="Evaluations",
        y_axis_label="Completed evaluations",
        metrics=(
            _metric(
                "search.evaluations",
                "Evaluations",
                "Total candidate evaluations completed since the run started.",
                "evaluations",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.RUN,
                "progress",
            ),
        ),
        groups=(
            _metric_group(
                "progress",
                "Evaluation progress",
                "Completed evaluations relative to the configured termination budget.",
            ),
        ),
    ),
    "archive_coverage": ObserverPresentation(
        view_kind=ObserverViewKind.SERIES,
        title="Archive state",
        metric_patterns=("archive.occupied_cells", "archive.repertoire_size"),
        empty_message="Archive metrics appear after the first archive update.",
        x_axis_label="Evaluations",
        y_axis_label="Current retained count",
        metrics=(
            _metric(
                "archive.occupied_cells",
                "Occupied cells",
                "Descriptor cells that currently retain at least one candidate.",
                "cells",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.QD_CELLS,
                "cell occupancy",
            ),
            _metric(
                "archive.repertoire_size",
                "Repertoire size",
                "Candidates currently retained across all occupied cells.",
                "candidates",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.REPERTOIRE,
                "repertoire",
            ),
        ),
        groups=(
            _metric_group(
                "cell occupancy",
                "Cell occupancy",
                "Number of descriptor cells that currently contain at least one candidate.",
            ),
            _metric_group(
                "repertoire",
                "Repertoire size",
                "Number of candidates currently retained across the complete archive.",
            ),
        ),
    ),
    "candidate_outcomes": ObserverPresentation(
        view_kind=ObserverViewKind.STACKED_SERIES,
        title="Candidate outcomes",
        metric_patterns=("outcomes.*",),
        empty_message="Outcome rates appear after the first complete sampling window.",
        x_axis_label="Evaluations",
        y_axis_label="Share of archive decisions",
        metrics=(
            _metric(
                "outcomes.retained_rate",
                "Retained",
                "Candidates inserted into the archive, including insertions that evicted an elite.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "decision",
            ),
            _metric(
                "outcomes.rejected_invalid_rate",
                "Invalid",
                "Candidates not retained because their scientific evaluation was invalid.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "decision",
            ),
            _metric(
                "outcomes.rejected_duplicate_rate",
                "Duplicate",
                "Candidates not retained because the same bicluster was already in the cell.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "decision",
            ),
            _metric(
                "outcomes.rejected_dominated_rate",
                "Dominated",
                "Valid candidates dominated by an elite already retained in their cell.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "decision",
            ),
            _metric(
                "outcomes.rejected_capacity_rate",
                "Capacity",
                "Non-dominated candidates removed by bounded cell-capacity truncation.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "decision",
            ),
            _metric(
                "outcomes.rejected_out_of_bounds_rate",
                "Out of bounds",
                "Candidates whose descriptor values could not be mapped to an archive cell.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "decision",
            ),
        ),
        groups=(
            _metric_group(
                "decision",
                "Archive decisions",
                "Mutually exclusive outcomes for evaluated candidates. Rejected means not "
                "retained; only the invalid category represents a scientific evaluation failure.",
            ),
        ),
    ),
    "descriptor_distribution": ObserverPresentation(
        view_kind=ObserverViewKind.DISTRIBUTION,
        title="Descriptor distributions",
        metric_patterns=("descriptor.*",),
        empty_message="Descriptor summaries have not reached their sampling cadence.",
        x_axis_label="Evaluations",
        y_axis_label="Descriptor value",
        metrics=(
            _metric(
                "descriptor.*",
                "Descriptor distribution",
                "Distribution across every candidate in one complete sampling window.",
                "descriptor value",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "evaluated descriptors",
            ),
        ),
        groups=(
            _metric_group(
                "evaluated descriptors",
                "Descriptor distribution",
                "Minimum, quartiles, median, mean, and maximum across every candidate in "
                "the selected evaluation window.",
            ),
        ),
    ),
    "archive_descriptor_distribution": ObserverPresentation(
        view_kind=ObserverViewKind.DISTRIBUTION,
        title="Repertoire size distribution",
        metric_patterns=("archive_descriptor.*", "archive_cell.members.*"),
        empty_message="Repertoire summaries have not reached their sampling cadence.",
        x_axis_label="Evaluations",
        y_axis_label="Current repertoire value",
        metrics=(
            _metric(
                "archive_descriptor.*",
                "Retained descriptor distribution",
                "Distribution across candidates currently retained in the QD archive.",
                "descriptor value",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.CURRENT,
                MetricPopulation.REPERTOIRE,
                "retained descriptors",
            ),
            _metric(
                "archive_cell.members.*",
                "Members per occupied cell",
                "Distribution of retained candidate counts across currently occupied cells.",
                "candidates",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.CURRENT,
                MetricPopulation.QD_CELLS,
                "cell occupancy",
            ),
        ),
        groups=(
            _metric_group(
                "retained descriptors",
                "Retained candidate sizes",
                "Minimum, quartiles, median, mean, and maximum descriptor values in the "
                "current repertoire.",
            ),
            _metric_group(
                "cell occupancy",
                "Per-cell depth",
                "Minimum, quartiles, median, mean, and maximum retained members per occupied "
                "descriptor cell.",
            ),
        ),
    ),
    "objective_distribution": ObserverPresentation(
        view_kind=ObserverViewKind.DISTRIBUTION,
        title="Objective distributions",
        metric_patterns=("objective.*",),
        empty_message="Objective summaries have not reached their sampling cadence.",
        x_axis_label="Evaluations",
        y_axis_label="Objective value",
        metrics=(
            _metric(
                "objective.*",
                "Objective distribution",
                "Distribution across every candidate in one complete sampling window.",
                "objective value",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "evaluated objectives",
            ),
        ),
        groups=(
            _metric_group(
                "evaluated objectives",
                "Objective distribution",
                "Minimum, quartiles, median, mean, and maximum across every candidate in "
                "the selected evaluation window.",
            ),
        ),
    ),
    "emitter_credit": ObserverPresentation(
        view_kind=ObserverViewKind.GROUPED_SERIES,
        title="Emitter credit",
        metric_patterns=("emitter.*",),
        empty_message="Emitter credit is unavailable before scheduler feedback.",
        x_axis_label="Evaluations",
        y_axis_label="Selected emitter measure",
        metrics=(
            _metric(
                "emitter.*.credit",
                "Credit",
                "Current scheduler credit used to prioritize an emitter.",
                "credit",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.EMITTERS,
                "scheduler",
            ),
            _metric(
                "emitter.*.allocation_share",
                "Allocation share",
                "Emitter share of all scheduler allocations to date.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.EMITTERS,
                "scheduler",
            ),
            _metric(
                "emitter.*.retention_rate",
                "Retention rate",
                "Fraction of the emitter's recently evaluated candidates retained by the archive.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "yield",
            ),
            _metric(
                "emitter.*.new_cell_rate",
                "New-cell rate",
                "Fraction of the emitter's recent evaluations that discovered a new cell.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.ARCHIVE_DECISIONS,
                "yield",
            ),
        ),
        groups=(
            _metric_group(
                "scheduler",
                "Scheduler preference",
                "Current credit or cumulative allocation share used to distribute work among "
                "emitters.",
            ),
            _metric_group(
                "yield",
                "Recent emitter yield",
                "Fraction of each emitter's recent candidates retained or placed in a new cell.",
            ),
        ),
    ),
    "candidate_diversity": ObserverPresentation(
        view_kind=ObserverViewKind.SERIES,
        title="Candidate diversity",
        metric_patterns=("diversity.*",),
        empty_message="Diversity appears after enough candidates have been sampled.",
        x_axis_label="Evaluations",
        y_axis_label="Selected diversity measure",
        metrics=(
            _metric(
                "diversity.window_size",
                "Window size",
                "Candidates currently represented by the rolling diversity window.",
                "candidates",
                MetricValueKind.GAUGE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "window counts",
            ),
            _metric(
                "diversity.window_unique",
                "Window unique",
                "Distinct bicluster structures in the current window.",
                "candidates",
                MetricValueKind.GAUGE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "window counts",
            ),
            _metric(
                "diversity.distance_sample_size",
                "Distance sample size",
                "Deterministic subset used for the quadratic nearest-neighbour calculation.",
                "candidates",
                MetricValueKind.GAUGE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "window counts",
            ),
            _metric(
                "diversity.cumulative_unique",
                "Cumulative unique",
                "Distinct bicluster structures observed since the run started.",
                "candidates",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.EVALUATED_CANDIDATES,
                "cumulative counts",
            ),
            _metric(
                "diversity.window_duplicate_ratio",
                "Window duplicate ratio",
                "Fraction of repeated structures in the current candidate window.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "window ratios",
            ),
            _metric(
                "diversity.cumulative_duplicate_ratio",
                "Cumulative duplicate ratio",
                "Fraction of all evaluated structures that repeated a previously observed one.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.EVALUATED_CANDIDATES,
                "cumulative ratios",
            ),
            _metric(
                "diversity.nearest_distance.*",
                "Nearest structural distance",
                "Distribution of nearest-neighbour row/column Jaccard distances.",
                "distance",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "distances",
            ),
        ),
        groups=(
            _metric_group(
                "window counts",
                "Window structures",
                "Candidate and unique-structure counts in the current rolling window.",
            ),
            _metric_group(
                "cumulative counts",
                "Cumulative structures",
                "Distinct bicluster structures observed since the run started.",
            ),
            _metric_group(
                "window ratios",
                "Window duplication",
                "Fraction of repeated structures in the current rolling window.",
            ),
            _metric_group(
                "cumulative ratios",
                "Cumulative duplication",
                "Fraction of all evaluated structures that repeat a previous structure.",
            ),
            _metric_group(
                "distances",
                "Structural distance",
                "Nearest-neighbour row and column Jaccard distance in the sampled window.",
            ),
        ),
    ),
    "runtime_throughput": ObserverPresentation(
        view_kind=ObserverViewKind.KPI_SERIES,
        title="Runtime throughput",
        metric_patterns=("runtime.*",),
        empty_message="Runtime metrics appear after the first evaluated batch.",
        x_axis_label="Evaluations",
        y_axis_label="Selected runtime measure",
        metrics=(
            _metric(
                "runtime.evaluations_per_second",
                "Evaluation throughput",
                "Candidate evaluations completed per wall-clock second in the latest batch.",
                "evaluations/second",
                MetricValueKind.RATE,
                MetricTemporalScope.BATCH,
                MetricPopulation.RUN,
                "throughput",
            ),
            _metric(
                "runtime.worker_count",
                "Workers",
                "Workers configured for the evaluation executor.",
                "workers",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.PROCESS,
                "concurrency",
            ),
            _metric(
                "runtime.peak_in_flight",
                "Peak in flight",
                "Largest number of evaluations simultaneously in flight in the latest batch.",
                "evaluations",
                MetricValueKind.GAUGE,
                MetricTemporalScope.BATCH,
                MetricPopulation.PROCESS,
                "concurrency",
            ),
        ),
        groups=(
            _metric_group(
                "throughput",
                "Evaluation throughput",
                "Candidate evaluations completed per wall-clock second in each batch.",
            ),
            _metric_group(
                "concurrency",
                "Evaluation concurrency",
                "Configured worker use and peak simultaneous evaluations in each batch.",
            ),
        ),
    ),
    "component_timing": ObserverPresentation(
        view_kind=ObserverViewKind.SERIES,
        title="Component timing",
        metric_patterns=("timing.*",),
        empty_message="Component timings appear after setup or the first sampling window.",
        x_axis_label="Evaluations",
        y_axis_label="Seconds",
        metrics=(
            _metric(
                "timing.setup.*",
                "Setup duration",
                "One-time wall-clock duration of loading, preprocessing, or search initialization.",
                "seconds",
                MetricValueKind.DELTA,
                MetricTemporalScope.CURRENT,
                MetricPopulation.RUN,
                "setup",
            ),
            _metric(
                "timing.search.*",
                "Search-phase duration",
                "Total wall-clock duration of a search phase in the latest sampling window.",
                "seconds",
                MetricValueKind.DELTA,
                MetricTemporalScope.WINDOW,
                MetricPopulation.RUN,
                "search phases",
            ),
            _metric(
                "timing.scientific.*",
                "Scientific component duration",
                "Accumulated worker time spent in one objective, descriptor, constraint, or "
                "validity policy during the latest sampling window. Parallel work is summed.",
                "seconds",
                MetricValueKind.DELTA,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "scientific components",
            ),
            _metric(
                "timing.component.*",
                "Pipeline component duration",
                "Accumulated time reported by initializers, archives, emitters, schedulers, and "
                "other instrumented search components during the latest sampling window.",
                "seconds",
                MetricValueKind.DELTA,
                MetricTemporalScope.WINDOW,
                MetricPopulation.RUN,
                "pipeline components",
            ),
            _metric(
                "timing.candidate_evaluation.*",
                "Candidate evaluation latency",
                "Mean or 95th-percentile wall-clock latency of individual candidate evaluations "
                "in the latest sampling window.",
                "seconds",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "candidate latency",
            ),
            _metric(
                "timing.observer.*",
                "Observer duration",
                "Total observer callback time measured by the event dispatcher in the latest "
                "sampling window.",
                "seconds",
                MetricValueKind.DELTA,
                MetricTemporalScope.WINDOW,
                MetricPopulation.RUN,
                "observers",
            ),
            _metric(
                "timing.output.*",
                "Output duration",
                "One-time wall-clock duration of final selection or artifact serialization.",
                "seconds",
                MetricValueKind.DELTA,
                MetricTemporalScope.CURRENT,
                MetricPopulation.RUN,
                "output",
            ),
        ),
        groups=(
            _metric_group(
                "setup",
                "Setup",
                "One-time loading, preprocessing, and search-engine initialization cost.",
            ),
            _metric_group(
                "search phases",
                "Search phases",
                "Candidate generation, evaluation batches, and search-state update time in each "
                "sampling window.",
            ),
            _metric_group(
                "scientific components",
                "Scientific components",
                "Accumulated worker time attributed to each objective, descriptor, constraint, "
                "and validity policy. Parallel work may exceed elapsed wall time.",
            ),
            _metric_group(
                "pipeline components",
                "Pipeline components",
                "Time attributed inside the initializer, archive, emitters, scheduler, and other "
                "instrumented search components.",
            ),
            _metric_group(
                "candidate latency",
                "Candidate latency",
                "Mean and 95th-percentile wall-clock latency for individual evaluations.",
            ),
            _metric_group(
                "observers",
                "Observers",
                "Observer callback overhead measured independently by the asynchronous event "
                "dispatcher.",
            ),
            _metric_group(
                "output",
                "Output",
                "Final selection and canonical artifact serialization cost.",
            ),
        ),
    ),
    "evaluation_issues": ObserverPresentation(
        view_kind=ObserverViewKind.SERIES,
        title="Evaluation issues",
        metric_patterns=("evaluation.valid_rate", "evaluation.invalid_rate", "evaluation.issue.*"),
        empty_message="No scientific evaluation issues have been observed.",
        x_axis_label="Evaluations",
        y_axis_label="Share of evaluated candidates",
        metrics=(
            _metric(
                "evaluation.valid_rate",
                "Valid",
                "Candidates with a complete valid scientific evaluation in the latest window.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "validity",
            ),
            _metric(
                "evaluation.invalid_rate",
                "Invalid",
                "Candidates with at least one scientific evaluation issue in the latest window.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "validity",
            ),
            _metric(
                "evaluation.issue.*",
                "Issue prevalence",
                "Candidates affected by a specific issue; issue categories may overlap.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.EVALUATED_CANDIDATES,
                "issues",
            ),
        ),
        groups=(
            _metric_group(
                "validity",
                "Evaluation validity",
                "Share of candidates with complete or invalid scientific evaluations in each "
                "sampling window.",
            ),
            _metric_group(
                "issues",
                "Issue prevalence",
                "Share of candidates affected by each issue. A candidate may contribute to "
                "more than one issue category.",
            ),
        ),
    ),
    "qd_archive_diagnostics": ObserverPresentation(
        view_kind=ObserverViewKind.HEATMAP,
        title="QD archive diagnostics",
        metric_patterns=("qd.*",),
        empty_message="Cell diagnostics appear after archive sampling.",
        x_axis_label="First descriptor bin",
        y_axis_label="Second descriptor bin",
        metrics=(
            _metric(
                "qd.visited_cells",
                "Visited cells",
                "Descriptor cells that have received at least one mapped insertion attempt.",
                "cells",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "coverage",
            ),
            _metric(
                "qd.unmapped_attempts",
                "Unmapped attempts",
                "Archive decisions without a valid descriptor-cell coordinate.",
                "candidates",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.ARCHIVE_DECISIONS,
                "coverage",
            ),
            _metric(
                "qd.cell_attempts.*",
                "Cell-attempt distribution",
                "Distribution of mapped candidate counts across visited descriptor cells.",
                "candidates",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "cell summaries",
            ),
            _metric(
                "qd.cell_acceptance_ratio.*",
                "Cell-retention distribution",
                "Distribution of cumulative retention ratios across visited cells.",
                "ratio",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "cell summaries",
            ),
            _metric(
                "qd.cell_stagnation_evaluations.*",
                "Cell-stagnation distribution",
                "Distribution of evaluations since the latest accepted candidate per cell.",
                "evaluations",
                MetricValueKind.DISTRIBUTION,
                MetricTemporalScope.CURRENT,
                MetricPopulation.QD_CELLS,
                "cell summaries",
            ),
            _metric(
                "qd.cell.*.attempts",
                "Insertion attempts",
                "Candidates mapped to each descriptor cell since the run started.",
                "candidates",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "cell map",
            ),
            _metric(
                "qd.cell.*.accepted",
                "Retained candidates",
                "Candidates retained at least once in each descriptor cell.",
                "candidates",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "cell map",
            ),
            _metric(
                "qd.cell.*.acceptance_ratio",
                "Retention ratio",
                "Fraction of mapped candidates retained at least once in each cell.",
                "ratio",
                MetricValueKind.RATE,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "cell map",
            ),
            _metric(
                "qd.cell.*.evictions",
                "Elite evictions",
                "Previously retained candidates displaced in each descriptor cell.",
                "candidates",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.QD_CELLS,
                "cell map",
            ),
            _metric(
                "qd.cell.*.stagnation_evaluations",
                "Stagnation",
                "Evaluations elapsed since each cell last accepted a candidate.",
                "evaluations",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.QD_CELLS,
                "cell map",
            ),
        ),
        groups=(
            _metric_group(
                "coverage",
                "Archive coverage",
                "Visited descriptor cells and candidates that could not be mapped to a cell.",
            ),
            _metric_group(
                "cell summaries",
                "Cell summary distribution",
                "Distribution of visits, retention, or stagnation across descriptor cells.",
            ),
            _metric_group(
                "cell map",
                "Cell diagnostic map",
                "Selected visit, retention, turnover, or stagnation measure for every "
                "two-dimensional archive cell.",
            ),
        ),
    ),
    "resource_usage": ObserverPresentation(
        view_kind=ObserverViewKind.KPI_SERIES,
        title="Resource usage",
        metric_patterns=("resource.*",),
        empty_message="Resource samples have not reached their sampling cadence.",
        x_axis_label="Evaluations",
        y_axis_label="Resource value",
        metrics=(
            _metric(
                "resource.process_cpu_seconds",
                "Process CPU time",
                "Cumulative CPU time consumed by the monitored process.",
                "seconds",
                MetricValueKind.COUNTER,
                MetricTemporalScope.CUMULATIVE,
                MetricPopulation.PROCESS,
                "cpu time",
            ),
            _metric(
                "resource.interval_cpu_percent",
                "CPU utilization",
                "Process CPU utilization over the latest sampling interval.",
                "percent",
                MetricValueKind.RATE,
                MetricTemporalScope.WINDOW,
                MetricPopulation.PROCESS,
                "cpu utilization",
            ),
            _metric(
                "resource.resident_memory_bytes",
                "Resident memory",
                "Current resident memory of the monitored process.",
                "bytes",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.PROCESS,
                "memory",
            ),
            _metric(
                "resource.active_threads",
                "Active threads",
                "Current active thread count in the monitored process.",
                "threads",
                MetricValueKind.GAUGE,
                MetricTemporalScope.CURRENT,
                MetricPopulation.PROCESS,
                "threads",
            ),
        ),
        groups=(
            _metric_group(
                "cpu time",
                "CPU time",
                "Cumulative CPU time consumed by the coordinator process.",
            ),
            _metric_group(
                "cpu utilization",
                "CPU utilization",
                "Coordinator-process CPU use during each sampling interval.",
            ),
            _metric_group(
                "memory",
                "Resident memory",
                "Physical memory currently held by the coordinator process.",
            ),
            _metric_group(
                "threads",
                "Active threads",
                "Threads currently active in the coordinator process.",
            ),
        ),
    ),
}
