"""Immutable models shared by SALVI subsystems."""

from __future__ import annotations

import hashlib
import math
from datetime import UTC, datetime
from functools import cached_property
from pathlib import Path
from typing import Annotated, Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from salvi.domain.enums import (
    ColumnKind,
    EvaluationIssueCode,
    EventType,
    ObjectiveDirection,
    ParameterScale,
    PatternKind,
    RunStatus,
)


class FrozenModel(BaseModel):
    """Base model that rejects unknown fields and mutation."""

    model_config = ConfigDict(frozen=True, extra="forbid")


class ColumnMetadata(FrozenModel):
    index: Annotated[int, Field(ge=0)]
    name: str = Field(min_length=1)
    kind: ColumnKind
    categories: tuple[str, ...] = ()

    @model_validator(mode="after")
    def validate_categories(self) -> ColumnMetadata:
        if self.kind is ColumnKind.CATEGORICAL and not self.categories:
            raise ValueError("categorical columns must declare at least one category")
        if self.kind is not ColumnKind.CATEGORICAL and self.categories:
            raise ValueError("only categorical columns may declare categories")
        if len(set(self.categories)) != len(self.categories):
            raise ValueError("column categories must be unique")
        return self


class Dataset(FrozenModel):
    identifier: str = Field(min_length=1)
    bundle_path: Path
    row_count: Annotated[int, Field(ge=1)]
    column_count: Annotated[int, Field(ge=1)]
    columns: tuple[ColumnMetadata, ...]

    @model_validator(mode="after")
    def validate_shape(self) -> Dataset:
        if len(self.columns) != self.column_count:
            raise ValueError("column metadata count does not match column_count")
        if tuple(column.index for column in self.columns) != tuple(range(self.column_count)):
            raise ValueError("column indices must be contiguous and zero-based")
        names = tuple(column.name for column in self.columns)
        if len(set(names)) != len(names):
            raise ValueError("column names must be unique")
        return self


def _validate_indices(indices: tuple[int, ...], label: str) -> tuple[int, ...]:
    if not indices:
        raise ValueError(f"{label} must not be empty")
    if any(index < 0 for index in indices):
        raise ValueError(f"{label} must be non-negative")
    if tuple(sorted(set(indices))) != indices:
        raise ValueError(f"{label} must be sorted and unique")
    return indices


class Bicluster(FrozenModel):
    row_indices: tuple[int, ...]
    column_indices: tuple[int, ...]

    @field_validator("row_indices")
    @classmethod
    def validate_rows(cls, value: tuple[int, ...]) -> tuple[int, ...]:
        return _validate_indices(value, "row_indices")

    @field_validator("column_indices")
    @classmethod
    def validate_columns(cls, value: tuple[int, ...]) -> tuple[int, ...]:
        return _validate_indices(value, "column_indices")

    @cached_property
    def signature(self) -> str:
        material = (
            f"r:{','.join(map(str, self.row_indices))}|c:{','.join(map(str, self.column_indices))}"
        )
        return hashlib.sha256(material.encode("ascii")).hexdigest()


class CandidateProvenance(FrozenModel):
    """Exact origin of a candidate generated by initialization or an emitter."""

    producer: str = Field(min_length=1)
    operation: str = Field(min_length=1)
    sequence: Annotated[int, Field(ge=0)]
    parent_identifiers: tuple[str, ...] = ()
    pattern_hint: PatternKind | None = None
    target_archive_coordinate: tuple[Annotated[int, Field(ge=0)], ...] | None = None
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("producer", "operation")
    @classmethod
    def reject_blank_text(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("candidate provenance text must not be blank")
        return value

    @field_validator("parent_identifiers")
    @classmethod
    def validate_parents(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        if any(not identifier.strip() for identifier in value):
            raise ValueError("candidate parent identifiers must not be blank")
        if len(set(value)) != len(value):
            raise ValueError("candidate parent identifiers must be unique")
        return value

    @field_validator("target_archive_coordinate")
    @classmethod
    def validate_target_coordinate(
        cls,
        value: tuple[int, ...] | None,
    ) -> tuple[int, ...] | None:
        if value is not None and not value:
            raise ValueError("target archive coordinates must contain at least one axis")
        return value


class Candidate(FrozenModel):
    identifier: str = Field(default_factory=lambda: str(uuid4()), min_length=1)
    bicluster: Bicluster
    generation: Annotated[int, Field(ge=0)] = 0
    provenance: CandidateProvenance | None = None


class NamedValue(FrozenModel):
    name: str = Field(min_length=1)
    value: float

    @field_validator("value")
    @classmethod
    def require_finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("values must be finite")
        return value


class EvaluationIssue(FrozenModel):
    code: EvaluationIssueCode
    message: str = Field(min_length=1)
    column_index: Annotated[int, Field(ge=0)] | None = None
    pattern: PatternKind | None = None


class ColumnObjectiveValue(FrozenModel):
    column_index: Annotated[int, Field(ge=0)]
    value: float
    valid: bool = True
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("value")
    @classmethod
    def require_finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("column objective values must be finite")
        return value


class ObjectiveResult(FrozenModel):
    value: float
    columns: tuple[ColumnObjectiveValue, ...]
    issues: tuple[EvaluationIssue, ...] = ()
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("value")
    @classmethod
    def require_finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("objective results must be finite")
        return value

    @model_validator(mode="after")
    def validate_columns(self) -> ObjectiveResult:
        indices = tuple(column.column_index for column in self.columns)
        if tuple(sorted(set(indices))) != indices:
            raise ValueError("objective column values must be sorted and unique")
        return self


class ObjectiveValue(NamedValue):
    direction: ObjectiveDirection
    columns: tuple[ColumnObjectiveValue, ...] = ()
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()


class ConstraintResult(FrozenModel):
    """Signed constraint result following the ``value <= 0`` convention."""

    value: float
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("value")
    @classmethod
    def require_finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("constraint results must be finite")
        return value

    @property
    def violation(self) -> float:
        return max(0.0, self.value)


class ConstraintValue(NamedValue):
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @property
    def violation(self) -> float:
        return max(0.0, self.value)

    @property
    def feasible(self) -> bool:
        return self.value <= 0.0


class PatternCandidateFit(FrozenModel):
    pattern: PatternKind
    error: Annotated[float, Field(ge=0.0, le=1.0)]
    parameter: bool | float | str | None = None
    parameter_scale: ParameterScale = ParameterScale.NONE
    source_support: Annotated[int, Field(ge=0)] = 0
    available_support: Annotated[int, Field(ge=0)] = 0
    prototype_support: Annotated[int, Field(ge=0)] = 0
    valid: bool = True
    issue_code: EvaluationIssueCode | None = None
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("parameter")
    @classmethod
    def validate_parameter(cls, value: bool | float | str | None) -> bool | float | str | None:
        if isinstance(value, float) and not math.isfinite(value):
            raise ValueError("numeric pattern parameters must be finite")
        return value

    @model_validator(mode="after")
    def validate_support(self) -> PatternCandidateFit:
        if self.source_support > self.available_support:
            raise ValueError("source support cannot exceed available support")
        if self.prototype_support > self.available_support:
            raise ValueError("prototype support cannot exceed available support")
        if (self.valid and self.issue_code is not None) or (
            not self.valid and self.issue_code is None
        ):
            raise ValueError(
                "valid pattern alternatives cannot have an issue and invalid ones require one"
            )
        return self


class ColumnPatternFit(FrozenModel):
    column_index: Annotated[int, Field(ge=0)]
    pattern: PatternKind | None
    group_identifier: str | None = None
    error: Annotated[float, Field(ge=0.0, le=1.0)]
    parameter: bool | float | str | None = None
    parameter_scale: ParameterScale = ParameterScale.NONE
    source_support: Annotated[int, Field(ge=0)] = 0
    available_support: Annotated[int, Field(ge=0)] = 0
    prototype_support: Annotated[int, Field(ge=0)] = 0
    alternatives: tuple[PatternCandidateFit, ...] = ()
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("parameter")
    @classmethod
    def validate_parameter(cls, value: bool | float | str | None) -> bool | float | str | None:
        if isinstance(value, float) and not math.isfinite(value):
            raise ValueError("numeric pattern parameters must be finite")
        return value

    @model_validator(mode="after")
    def validate_assignment(self) -> ColumnPatternFit:
        if self.source_support > self.available_support:
            raise ValueError("source support cannot exceed available support")
        if self.prototype_support > self.available_support:
            raise ValueError("prototype support cannot exceed available support")
        patterns = tuple(alternative.pattern for alternative in self.alternatives)
        if len(set(patterns)) != len(patterns):
            raise ValueError("pattern alternatives must be unique")
        if self.pattern is None:
            if self.error != 1.0 or self.parameter is not None or self.group_identifier is not None:
                raise ValueError("unassigned columns require error 1, no parameter, and no group")
        elif self.pattern not in patterns:
            raise ValueError("assigned pattern must be present among alternatives")
        return self


class PatternGroupFit(FrozenModel):
    identifier: str = Field(min_length=1)
    pattern: PatternKind
    column_indices: tuple[int, ...]
    row_parameters: tuple[tuple[int, float], ...] = ()
    iterations: Annotated[int, Field(ge=0)] = 0
    converged: bool = True
    diagnostics: tuple[tuple[str, float | int | str | bool | None], ...] = ()

    @field_validator("column_indices")
    @classmethod
    def validate_columns(cls, value: tuple[int, ...]) -> tuple[int, ...]:
        return _validate_indices(value, "pattern group column_indices")

    @field_validator("row_parameters")
    @classmethod
    def validate_rows(cls, value: tuple[tuple[int, float], ...]) -> tuple[tuple[int, float], ...]:
        indices = tuple(row for row, _ in value)
        if tuple(sorted(set(indices))) != indices:
            raise ValueError("pattern row parameters must be sorted and unique")
        if any(row < 0 or not math.isfinite(parameter) for row, parameter in value):
            raise ValueError("pattern row parameters must have valid indices and values")
        return value


class PatternFit(FrozenModel):
    candidate_signature: str = Field(min_length=64, max_length=64)
    row_indices: tuple[int, ...]
    column_indices: tuple[int, ...]
    columns: tuple[ColumnPatternFit, ...]
    groups: tuple[PatternGroupFit, ...] = ()
    issues: tuple[EvaluationIssue, ...] = ()

    @field_validator("row_indices")
    @classmethod
    def validate_rows(cls, value: tuple[int, ...]) -> tuple[int, ...]:
        return _validate_indices(value, "pattern fit row_indices")

    @field_validator("column_indices")
    @classmethod
    def validate_column_indices(cls, value: tuple[int, ...]) -> tuple[int, ...]:
        return _validate_indices(value, "pattern fit column_indices")

    @model_validator(mode="after")
    def validate_details(self) -> PatternFit:
        fitted = tuple(column.column_index for column in self.columns)
        if fitted != self.column_indices:
            raise ValueError("pattern columns must align with selected columns")
        assigned = {column.column_index: column.pattern for column in self.columns}
        assigned_groups = {column.column_index: column.group_identifier for column in self.columns}
        group_columns: set[int] = set()
        identifiers: set[str] = set()
        for group in self.groups:
            if group.identifier in identifiers:
                raise ValueError("pattern group identifiers must be unique")
            identifiers.add(group.identifier)
            referenced_columns = {
                column_index
                for column_index, identifier in assigned_groups.items()
                if identifier == group.identifier
            }
            if referenced_columns != set(group.column_indices):
                raise ValueError("pattern group membership must be declared by exactly its columns")
            for column_index in group.column_indices:
                if column_index in group_columns:
                    raise ValueError("a column cannot belong to multiple pattern groups")
                if assigned.get(column_index) is not group.pattern:
                    raise ValueError("pattern groups must match column assignments")
                group_columns.add(column_index)
            if any(row not in self.row_indices for row, _ in group.row_parameters):
                raise ValueError("pattern row parameters must reference selected rows")
        unknown_groups = {
            identifier
            for identifier in assigned_groups.values()
            if identifier is not None and identifier not in identifiers
        }
        if unknown_groups:
            raise ValueError("column pattern assignments reference an unknown group")
        return self

    @property
    def valid(self) -> bool:
        return not self.issues and all(column.pattern is not None for column in self.columns)


class FinalSelectionProvenance(FrozenModel):
    """Trace one reported bicluster back to the retained search repertoire."""

    selector: str = Field(min_length=1)
    group_identifier: str = Field(min_length=1)
    selection_rank: Annotated[int, Field(ge=0)]
    quality_score: Annotated[float, Field(ge=0.0, le=1.0)]
    novelty_score: Annotated[float, Field(ge=0.0, le=1.0)]
    marginal_gain: Annotated[float, Field(ge=0.0, le=1.0)]
    source_candidate_identifiers: tuple[str, ...]
    source_archive_coordinates: tuple[tuple[int, ...], ...] = ()

    @model_validator(mode="after")
    def validate_sources(self) -> FinalSelectionProvenance:
        if not self.source_candidate_identifiers:
            raise ValueError("final-selection provenance requires at least one source candidate")
        if (
            tuple(sorted(set(self.source_candidate_identifiers)))
            != self.source_candidate_identifiers
        ):
            raise ValueError("source candidate identifiers must be sorted and unique")
        if tuple(sorted(set(self.source_archive_coordinates))) != self.source_archive_coordinates:
            raise ValueError("source archive coordinates must be sorted and unique")
        if any(
            not coordinate or any(index < 0 for index in coordinate)
            for coordinate in self.source_archive_coordinates
        ):
            raise ValueError("source archive coordinates must contain non-negative indices")
        dimensions = {len(coordinate) for coordinate in self.source_archive_coordinates}
        if len(dimensions) > 1:
            raise ValueError("source archive coordinates must share one dimensionality")
        return self


class Evaluation(FrozenModel):
    candidate: Candidate
    objectives: tuple[ObjectiveValue, ...]
    descriptors: tuple[NamedValue, ...]
    constraints: tuple[ConstraintValue, ...] = ()
    pattern_fit: PatternFit | None = None
    issues: tuple[EvaluationIssue, ...] = ()
    archive_coordinate: tuple[int, ...] | None = None
    final_selection: FinalSelectionProvenance | None = None

    @model_validator(mode="after")
    def validate_names(self) -> Evaluation:
        for values, label in (
            (self.objectives, "objective"),
            (self.descriptors, "descriptor"),
            (self.constraints, "constraint"),
        ):
            names = tuple(item.name for item in values)
            if len(set(names)) != len(names):
                raise ValueError(f"{label} names must be unique")
        selected_columns = self.candidate.bicluster.column_indices
        for objective in self.objectives:
            explained = tuple(column.column_index for column in objective.columns)
            if explained and explained != selected_columns:
                raise ValueError("objective column values must align with selected columns")
        if self.pattern_fit is not None:
            if self.pattern_fit.candidate_signature != self.candidate.bicluster.signature:
                raise ValueError("pattern fit does not match its evaluation candidate")
            if (
                self.pattern_fit.row_indices != self.candidate.bicluster.row_indices
                or self.pattern_fit.column_indices != selected_columns
            ):
                raise ValueError("pattern fit indices do not match its evaluation candidate")
        if self.archive_coordinate is not None and (
            not self.archive_coordinate or any(index < 0 for index in self.archive_coordinate)
        ):
            raise ValueError("archive coordinates must contain non-negative indices")
        if (
            self.final_selection is not None
            and self.candidate.identifier not in self.final_selection.source_candidate_identifiers
        ):
            raise ValueError("a selected bicluster must reference itself in its provenance")
        return self

    @property
    def valid(self) -> bool:
        return not self.issues and (self.pattern_fit is None or self.pattern_fit.valid)

    @property
    def constraint_violation(self) -> float:
        return sum(constraint.violation for constraint in self.constraints)

    @property
    def feasible(self) -> bool:
        return self.valid and self.constraint_violation == 0.0

    @cached_property
    def mean_column_losses(self) -> dict[int, float]:
        """Mean direction-aware objective loss for each explained column."""

        values: dict[int, list[float]] = {}
        for objective in self.objectives:
            for column in objective.columns:
                loss = (
                    column.value
                    if objective.direction is ObjectiveDirection.MINIMIZE
                    else 1.0 - column.value
                )
                values.setdefault(column.column_index, []).append(loss)
        return {
            column_index: float(sum(losses) / len(losses))
            for column_index, losses in values.items()
        }


class Repertoire(FrozenModel):
    evaluations: tuple[Evaluation, ...] = ()


class RunEvent(FrozenModel):
    sequence: Annotated[int, Field(ge=1)] | None = None
    event_type: EventType
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    payload: dict[str, Any] = Field(default_factory=dict)


class RunMetric(FrozenModel):
    sequence: Annotated[int, Field(ge=1)]
    event_sequence: Annotated[int, Field(ge=1)] | None = None
    name: str = Field(min_length=1)
    value: float
    step: Annotated[int, Field(ge=0)] | None = None

    @field_validator("value")
    @classmethod
    def validate_value(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("metric values must be finite")
        return value


class MetricSample(FrozenModel):
    """Observer-produced metric awaiting durable sequence assignment."""

    name: str = Field(min_length=1)
    value: float
    step: Annotated[int, Field(ge=0)] | None = None

    @field_validator("value")
    @classmethod
    def validate_value(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("metric sample values must be finite")
        return value


class RunArtifact(FrozenModel):
    identifier: str = Field(min_length=1)
    path: Path
    media_type: str = Field(min_length=1)
    checksum: str = Field(pattern=r"^[0-9a-f]{64}$")
    event_sequence: Annotated[int, Field(ge=1)] | None = None


class RunResult(FrozenModel):
    status: RunStatus
    output_directory: Path
    event_store: Path
    repertoire: Repertoire = Field(default_factory=Repertoire)
    message: str | None = None


__all__ = [
    "Bicluster",
    "Candidate",
    "CandidateProvenance",
    "ColumnMetadata",
    "ColumnObjectiveValue",
    "ColumnPatternFit",
    "Dataset",
    "Evaluation",
    "EvaluationIssue",
    "FinalSelectionProvenance",
    "FrozenModel",
    "MetricSample",
    "NamedValue",
    "ObjectiveResult",
    "ObjectiveValue",
    "PatternCandidateFit",
    "PatternFit",
    "PatternGroupFit",
    "Repertoire",
    "RunArtifact",
    "RunEvent",
    "RunMetric",
    "RunResult",
]
